# Question 1 & 3 / 6.3 Textbook

In [ ]:
import numpy as np
from numpy import linalg as la

# Our Transition Matrix here:
$\begin{pmatrix} 
    p_{AA}&p_{AB}&p_{AD} \\
    p_{BA}&p_{BB}&p_{BD} \\
    p_{DA}&p_{DB}&p_{DD} \end{pmatrix}$
    

In [ ]:
P = np.array([[0.95,0.045,0.005],[0.00,0.975,0.025],[0,0,1]])
print(P)
print(P.shape)

## Simple P after 2 states
$ P^2 = {\begin{pmatrix} 
    p_{AA}&p_{AB}&p_{AD} \\
    p_{BA}&p_{BB}&p_{BD} \\
    p_{DA}&p_{DB}&p_{DD} \end{pmatrix}}^{ 2}$

In [ ]:
P_2 = la.matrix_power(P,2)
print(P_2)
print(P_2.shape)

## Let's Define a Function for P exponential

In [ ]:
def matrix_n(start,N):
    matrix_exp = la.matrix_power(start,N)
    return matrix_exp

In [ ]:
P_N = matrix_n(P,2)
print(P_N)
print(P_N.shape)

# What is the intuition when N gets larger and larger (long dated)
$ \lim_{N \to \infty} P^N $

## Let's set up some row vectors to define our Starting State

In [ ]:
State_A = np.array([1,0,0])
State_B = np.array([0,1,0])
State_D = np.array([0,0,1])

In [ ]:
print(State_A)
print("Start in A:",State_A)
print("Start in B:",State_B)
print("Start in D:",State_D)

In [ ]:
# Avoid "rank one" arrays


In [ ]:
print(State_A.shape)

In [ ]:
State_A = State_A.reshape(1,(State_A.shape[0]))
print(State_A.shape)

In [ ]:
State_B = State_B.reshape(1,(State_B.shape[0]))
State_D = State_D.reshape(1,(State_D.shape[0]))

print(State_B.shape)
print(State_D.shape)

## This row vector represents all the probabilities of each state after 2 periods after starting in A

In [ ]:
A_2 = np.dot(State_A,matrix_n(P,2))
print("Bond A probs after 2 years:", A_2)

# And after 10 periods

In [ ]:
A_10 = np.dot(State_A,matrix_n(P,10))
print("Bond A probs after 10 years:", A_10)

## Define some column vectors so we can utilise matrix algebra to calculate probabilies of certain states after n periods

In [ ]:
now_A = np.array([[1],[0],[0]])

now_B = np.array([[0],[1],[0]])

default = np.array([[0],[0],[1]])

now_A_or_B = np.array([[1],[1],[0]])

# check for rank 1

In [ ]:
print(now_A)
print(now_A.shape)
print(now_B.shape)
print(default.shape)

# Note Python Numpy is clever and does what is called "Broadcasting" so (1 - default) works

In [ ]:
print("default")
print(default)

print("1-default")
print(1-default)

print("Either A or B")
print(now_A_or_B)

## Need to post multiply [Bond row vector] * [Pn] with [column vector] to obtain n-state probs

In [ ]:
N = 2
print(matrix_n(P,N))

# Pre-multypying by Initial State A gets all probs for Now given started in State A

In [ ]:
print(np.dot(State_A,matrix_n(P,N)))

# Post multiply to extract probabilities of certain states now given started in State A
# The dimension of this will be 1 x 1

In [ ]:
Prob_A_still_A = np.dot(np.dot(State_A,matrix_n(P,N)),now_A)

Prob_A_now_B = np.dot(np.dot(State_A,matrix_n(P,N)),now_B)

Prob_A_default = np.dot(np.dot(State_A,matrix_n(P,N)),default)

Prob_A_inBorA = np.dot(np.dot(State_A,matrix_n(P,N)),now_A_or_B)

In [ ]:
print("Prob A still A:", Prob_A_still_A)
print("Prob A now B:" , Prob_A_now_B)
print("Prob A default:",Prob_A_default)
print("Prob A is B or A:", Prob_A_inBorA)
print("Prob A not default:",1-Prob_A_default)

## Lets work out probs of each state for Bond A for longer periods
See how the range works - the numbers make sense as P to the 0 is the identity matrix

In [ ]:
for n in range(0,10):
    prob_state_k = np.dot(State_A,matrix_n(P,n))
    print(n, prob_state_k)

# Here I have adjusted the range so it works for a sensible number of years for us

In [ ]:
for n in range(1,11):
    survive = np.dot(np.dot(State_A,matrix_n(P,n)),1-default)
    print(n, survive)

# Initialising a matrix dimensions 10 x 1

In [ ]:
X = np.zeros((10,1))
print(X)
print("Shape")
print(X.shape)

# Introduce a for loop and note reference elements for Numpy arrays start at 0
For j = 1 to n (Term of the bond is n periods) [k ratings states for bond]

$
P_{1,N} = \begin{pmatrix}1 & 0 & 0 & \cdots & 0\end{pmatrix}_{1xk}*
\begin{pmatrix} 
    p_{1,1} & p_{1,2} & p_{1,3} & \cdots & p_{1,k}\\
    p_{2,1} & p_{2,2} & p_{2,3} & \cdots & p_{1,k}\\
    \vdots  & \vdots  & \vdots & \ddots & \vdots \\
    p_{n,1} & p_{n,2} & p_{n,3} & \cdots & p_{n,k} 
    \end{pmatrix}^N * \begin{pmatrix}1 \\ 1 \\ 1 \\ \vdots \\ 0\end{pmatrix}_{nx1}$
    

In [ ]:
X = np.zeros((10,4))
for n in range(1,11):
    survive = np.dot(np.dot(State_A,matrix_n(P,n)),1-default)
    X[n-1,0] = survive
    if n < 10:
        X[n-1,1] = survive *3
    else:
        if n == 10:
            X[n-1,1] = survive * 103
    Risk_Adjusted_Cash_n = X[n-1,1]
    X[n-1,2] = 1.06**-n
    DF_n = X[n-1,2]
    X[n-1,3] = Risk_Adjusted_Cash_n * DF_n
print(X)
EQV = np.sum(X[:,3])
print("Bond Value:", EQV)

## We can generalise this for starting in A,B or D now, and for term, i, coupon and redemption

In [14]:
import numpy as np
from numpy import linalg as la

def starting_state(rating):
    if rating == 'A':
        return np.array([1,0,0])
    if rating == 'B':
        return np.array([0,1,0])
    if rating == 'D':
        return np.array([0,0,1])
    
def matrix_n(start,N):
    matrix_exp = la.matrix_power(start,N)
    return matrix_exp

def Value_My_Risky_Bond(rating, coupon, face, P, term, i, default):
    X = np.zeros((term,4))
    for n in range(1, term + 1):
        
        survive = np.dot(np.dot(starting_state(rating),matrix_n(P,n)),1-default)
        X[n-1,0] = survive
        
        if n < term:
            X[n-1,1] = survive * coupon
        else:
            if n == term:
                X[n-1,1] = survive * (face+coupon)
        Risk_Adjusted_Cash_n = X[n-1,1]
        
        X[n-1,2] = (1.+i)**-n
        DF_n = X[n-1,2]
        
        X[n-1,3] = Risk_Adjusted_Cash_n * DF_n
        
        EQV = np.sum(X[:,3])
        
    print("Doing some high-level calcs...")
    print(X)
    
    
    if EQV > 0:
        print("Your bond which might default is worth: ",EQV)
        print("Have a nice day")
    else:
        print("Your bond which will default is worth: ",EQV)
        print("Sorry, it looks your bond is worthless")
    return

P = np.array([[0.95, 0.045, 0.005],
              [0.00, 0.975, 0.025],
              [0.00, 0.000, 1.000]])

default = np.array([[0],[0],[1]])

Value_My_Risky_Bond('B',5,100,P,12,0.07, default)



Doing some high-level calcs...
[[  0.975        4.875        0.93457944   4.55607477]
 [  0.950625     4.753125     0.87343873   4.15156346]
 [  0.92685937   4.63429687   0.81629788   3.7829667 ]
 [  0.90368789   4.51843945   0.76289521   3.44709582]
 [  0.88109569   4.40547847   0.71298618   3.14104526]
 [  0.8590683    4.29534151   0.66634222   2.86216741]
 [  0.83759159   4.18795797   0.62274974   2.60804974]
 [  0.8166518    4.08325902   0.5820091    2.37649392]
 [  0.79623551   3.98117754   0.54393374   2.1654968 ]
 [  0.77632962   3.8816481    0.50834929   1.97323307]
 [  0.75692138   3.7846069    0.4750928    1.79803948]
 [  0.73799835  77.48982631   0.44401196  34.4064096 ]]
Your bond which might default is worth:  67.268636031
Have a nice day
